config/routes.rb
Rails.application.routes.draw do
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  root 'welcome#index'

  get "users/" => "users#index"
  get "users/new" => "users#new", as: :new_user
  get "users/:id" => "users#show", as: :user
  post "users/" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "items/" => "items#index"
  get "items/new" => "items#new", as: :new_item
  get "items/:id" => "items#show", as: :item
  post "items/" => "items#create"
  get "items/:id/edit" => "items#edit", as: :edit_item
  patch "items/:id" => "items#update"
  delete "items/:id" => "items#destroy"

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	belongs_to :orderline
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :orderlines
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
	belongs_to :order
	has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :items
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def create
		 @item = Item.new(item_params)

		if @item.save
		  redirect_to items_path
		else
		  render :new
		end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])

		if @item.update_attributes(item_params)
		redirect_to items_path
		else
		render :edit
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to items_path
	end

private
	def item_params
	  params.require(:item).permit(:item_name, :user_id, :orderline_id, :stock_quantity, :marked_price, :updated_at)
	end




end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@orders = Order.all
	end

	def show
		@orderline = Orderline.find(params[:id])
		@user = @orderline.order.user
		# @users = []
		# @orderline.items.each do |item|
		# 	@users << item.user.first_name
		# end

	end

	def new
		@orderline = Orderline.new
	end

	def create
		 @order = order.new(user_params)

		if @order.save
		  redirect_to orders_path
		else
		  render :new
		end
	end

	def edit
		@order = order.find(params[:id])
	end

	def update
		@order = order.find(params[:id])

		if @order.update_attributes(order_params)
		redirect_to orders_path
		else
		render :edit
		end
	end

	def destroy
		@order = order.find(params[:id])
		@order.destroy
		redirect_to orders_path
	end

private
	def order_params
	  params.require(:order).permit(:user_id, :created_at)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      # make a new key in our session object called :user_id
      # which gets stored in a cookie in our browser
      session[:user_id] = user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])

	end

	def new
		@user = User.new
	end

	def create
		 @user = User.new(user_params)

		if @user.save
		  redirect_to users_path
		else
		  render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)
		redirect_to users_path
		else
		render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

private
	def user_params
	  params.require(:user).permit(:first_name, :last_name, :date_of_birth, :email, :password, :password_digest)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
  		@current_user ||= User.find_by(id: session[:user_id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :stock_quantity %>
        <%= f.number_field :stock_quantity %>
    </div>

    <div>
        <%= f.label :marked_price %>
        <%= f.number_field :marked_price %>
    </div>


    <button> <%= f.submit "Submit!" %> </button>

<% end %>

app/views/items/_list.html.erb
<table>
	<tr> 
		<th> ID   </th>
		<th> Name </th>
		<th> Quantity </th>
		<th> Price </th>
	</tr>
    <% @items.each do |item| %>
		<tr>
			<td> <%= item.id %> </td>
			<td> <%= item.name %> </td>   
			<td> <%= item.stock_quantity %> </td>
			<td> <%= item.marked_price %> </td>
		</tr>
    <% end %>
</table>

app/views/items/edit.html.erb
<h1>Edit Item!</h1>

<%= render 'form'%>

app/views/items/index.html.erb
<h2>Items List</h2>

<%= render 'list'%>

app/views/items/new.html.erb
<h1>New Item!</h1>

<%= render 'form'%>

app/views/items/show.html.erb
<h1> <%= @item.item_name %> </h1>

<p>Item name is <%= @item.item_name %>. Item quantity is <%= @item.stock_quantity%>. Item price is <%= @item.marked_price %>. It belongs to <%= @item.user.first_name %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Business2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= params %>
<%= yield %>

</body>
</html>

app/views/orders/_list.html.erb
<table>
	<tr> 
		<th> ID   </th>

	</tr>
    <% @orders.each do |order| %>
		<tr>
			<td> <%= order.id %> </td>

		</tr>
    <% end %>
</table>

app/views/orders/index.html.erb
<h1> Orders </h1>

<%= render "list" %>

app/views/orders/new.html.erb
<h1>New Order!</h1>

app/views/orders/show.html.erb
<h1> Orderline ID: <%= @orderline.id %> </h1>

<p>Order Item name is 

<% @orderline.items.each do |item| %>
<%= item.name %>
<% end %>

Order Item quantity is <%= @orderline.quantity%>. Order Item price is <%= @orderline.selling_price %>. It belongs to <%= @user.first_name %> </p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>


    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :date_of_birth %>
        <%= f.date_field :date_of_birth %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>



    <button> <%= f.submit "Add new user!" %> </button>

<% end %>

app/views/users/_list.html.erb
	<table>
		<tr> 
			<th> First Name </th>
			<th> Last Name </th>
			<th> Date of Birth: </th>
			<th> Email: </th>

		<tr>
	    <% @users.each do |user| %>
			<tr>
				<td> <%= user.first_name %> </td>  
				<td> <%= user.last_name %> </td>
				<td> <%= user.date_of_birth %> </td>
				<td> <%= user.email %> </td>

			</tr>
	    <% end %>
	</table>

app/views/users/edit.html.erb
<h1>Edit User Profile!</h1>

	<%= render 'form' %>

app/views/users/index.html.erb
<% if current_user %>
<h2>Users List</h2>

  Logged in as: <%= current_user.first_name %> <%= link_to 'Log Out', logout_path, method: :delete %>
  <%= render 'list'%>
<% else %>
  <%= link_to 'Log In', login_path %>
  <%= link_to 'Sign Up', new_user_path %>
<% end %>

	

app/views/users/new.html.erb
<h1>Register a new User!</h1>

	<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.first_name %> </h1>

<p>User name is <%= @user.first_name %>. User ID is <%= @user.id%>. User DOB is <%= @user.date_of_birth %> <%= @user.first_name %> has items 
	<% @user.items.each do |item| %>
		<%= item.item_name %>.
	<% end %>

 </p>